### PR TITLE
Feature rl 6232576386 ideas page

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Take figma design of Ideas page live using drhci as a template

## Related Tickets & Documents
- Monday Task #6232576386
- https://blackberg-group.monday.com/boards/1931719392/pulses/6232576386

## QA Instructions, Screenshots, Recordings

Please take a look at usability and match to figma ( https://www.figma.com/design/9a5QzqXaRr2HhSI68lmk6I/IDEAS---Mockup?node-id=7-1425&t=olDHGHMehQ6Zy4Hc-0 )

There are some small issues to address still. I wanted to get eyes on to make sure the remaining edits are handled efficiently. 

## Changed Files in this Pull Request ##
- _includes/ideas/1_masthead.html
 - _includes/ideas/2_mission.html
 - _includes/ideas/3_news.html
 - _includes/ideas/4_director.html
 - _includes/ideas/5_connect.html
 - _site/assets/img/drhci
 - copy/bubble-lines-sm.svg
 - _site/assets/img/drhci
 - copy/bubble-lines.svg
 - _site/assets/img/drhci
 - copy/lindsay-reigler.jpg
 - _site/assets/img/drhci
 - copy/logo.svg
 - _site/assets/img/drhci
 - copy/masthead-image.jpg
 - _site/assets/img/drhci
 - copy/masthead-img.jpg
 - _site/assets/img/drhci
 - copy/masthead-img.png
 - _site/assets/img/drhci
 - copy/news/drhci-news-feet.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-feetpad.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-helpp.png
 - _site/assets/img/drhci
 - copy/news/drhci-news-parade.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-telehealth.png
 - _site/assets/img/drhci
 - copy/news/drhci-news-toes.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-walking.jpg
 - _site/assets/img/drhci
 - copy/news/rtm-empowers-veterans.jpg
 - _site/assets/img/drhci
 - copy/vha-drhci-logo.svg
 - _site/assets/img/ideas/Frame
 - 555.png
 - _site/assets/img/ideas/bubble-lines-sm.svg
 - _site/assets/img/ideas/bubble-lines.svg
 - _site/assets/img/ideas/kathryn-beckner.jpg
 - _site/assets/img/ideas/lindsay-reigler.jpg
 - _site/assets/img/ideas/logo.svg
 - _site/assets/img/ideas/masthead-image.jpg
 - _site/assets/img/ideas/masthead-img.jpg
 - _site/assets/img/ideas/masthead-img.png
 - _site/assets/img/ideas/news/drhci-news-feet.jpg
 - _site/assets/img/ideas/news/drhci-news-feetpad.jpg
 - _site/assets/img/ideas/news/drhci-news-helpp.png
 - _site/assets/img/ideas/news/drhci-news-parade.jpg
 - _site/assets/img/ideas/news/drhci-news-telehealth.png
 - _site/assets/img/ideas/news/drhci-news-toes.jpg
 - _site/assets/img/ideas/news/drhci-news-walking.jpg
 - _site/assets/img/ideas/news/ideas-news-1.png
 - _site/assets/img/ideas/news/ideas-news-2.png
 - _site/assets/img/ideas/news/ideas-news-3.png
 - _site/assets/img/ideas/news/rtm-empowers-veterans.jpg
 - _site/assets/img/ideas/stefan-ianchulev.jpg
 - _site/assets/img/ideas/vha-drhci-logo.svg
 - _site/assets/img/ideas/vha-ideas-logo.png
 - _site/assets/js/ideas-home-news.js
 - assets/img/ideas/bubble-lines-sm.svg
 - assets/img/ideas/bubble-lines.svg
 - assets/img/ideas/kathryn-beckner.jpg
 - assets/img/ideas/logo.svg
 - assets/img/ideas/masthead-image.jpg
 - assets/img/ideas/masthead-img.jpg
 - assets/img/ideas/masthead-img.png
 - assets/img/ideas/news/ideas-news-1.png
 - assets/img/ideas/news/ideas-news-2.png
 - assets/img/ideas/news/ideas-news-3.png
 - assets/img/ideas/stefan-ianchulev.jpg
 - assets/img/ideas/vha-ideas-logo.png
 - assets/js/ideas-home-news.js
 - _site/assets/css/styles.css
 - _site/assets/js/drhci-home-news.js
 - _site/assets/sass/vha/pages/drhci/connect/_index.scss
 - _site/assets/sass/vha/pages/drhci/masthead/_index.scss
 - _site/ideas/index.html
 - assets/css/styles.css
 - assets/sass/vha/pages/drhci/connect/_index.scss
 - assets/sass/vha/pages/drhci/masthead/_index.scss
 - ideas/index.html

### CODE REVIEW

**Comment by RyanCrux** [comment]
@will-bbg All set to take another look. Updated the page based on the word document details.

**Review by will-bbg — CHANGES_REQUESTED** [review]
- Add link to navigation
- Logo appears blurry on a retina screen. Please make the logo an svg like DRHCI
- Double check responsive layout in hero section. See screenshot: 
Screenshot 2024-05-21 at 7 53 30 AM

- Please use hero image from mockup, to remind the client we need the youtube url
- For the Bio images, please align them to the top of content, just like the Figma design

**Comment by RyanCrux** [comment]
QUICK LINK: https://www.dev-innovation.bgsandbox.com/ecosystem/views/national-centers/ideas/

* Add link to navigation
     -DONE

* Logo appears blurry on a retina screen. Please make the logo an svg like DRHCI     
     -DONE

* Double check responsive layout in hero section. See screenshot:
     -DONE

* Please use hero image from mockup, to remind the client we need the youtube url
     -DONE

* For the Bio images, please align them to the top of content, just like the Figma design. 
     - DONE

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
