### PR TITLE
Feat/rl 7374453745/necie landing page

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Development of NECIE page

## Related Tickets & Documents
- Monday Task: https://blackberg-group.monday.com/boards/1931719392/pulses/7374453745

## QA Instructions, Screenshots, Recordings

Review new page & compare to Figma: https://www.figma.com/design/36Ugn3IRxMRLNCPsdei8lK/NECIE?node-id=6032-75&node-type=FRAME&m=dev

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized 

## Changed Files in this Pull Request ##
- _includes/necie/1_masthead.html
 - _includes/necie/2_mission.html
 - _includes/necie/3_news.html
 - _includes/necie/4_director.html
 - _includes/necie/5_connect.html
 - _site/assets/img/drhci
 - copy/bubble-lines-sm.svg
 - _site/assets/img/drhci
 - copy/bubble-lines.svg
 - _site/assets/img/drhci
 - copy/lindsay-reigler.jpg
 - _site/assets/img/drhci
 - copy/logo.svg
 - _site/assets/img/drhci
 - copy/masthead-image.jpg
 - _site/assets/img/drhci
 - copy/masthead-img.jpg
 - _site/assets/img/drhci
 - copy/masthead-img.png
 - _site/assets/img/drhci
 - copy/news/drhci-news-feet.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-feetpad.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-helpp.png
 - _site/assets/img/drhci
 - copy/news/drhci-news-parade.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-telehealth.png
 - _site/assets/img/drhci
 - copy/news/drhci-news-toes.jpg
 - _site/assets/img/drhci
 - copy/news/drhci-news-walking.jpg
 - _site/assets/img/drhci
 - copy/news/rtm-empowers-veterans.jpg
 - _site/assets/img/drhci
 - copy/vha-drhci-logo.svg
 - _site/assets/img/necie/bubble-lines-sm.svg
 - _site/assets/img/necie/bubble-lines.svg
 - _site/assets/img/necie/genesis_de_la_cruz.jpg
 - _site/assets/img/necie/kindred_kern.jpg
 - _site/assets/img/necie/leandro_dasilva.jpg
 - _site/assets/img/necie/lindsay-reigler.jpg
 - _site/assets/img/necie/logo.svg
 - _site/assets/img/necie/masthead-image.jpg
 - _site/assets/img/necie/masthead-img.jpg
 - _site/assets/img/necie/masthead-img.png
 - _site/assets/img/necie/news/give.jpg
 - _site/assets/img/necie/news/hero.jpg
 - _site/assets/img/necie/news/mobius-mobility.jpg
 - _site/assets/img/necie/news/move-the-sample.jpg
 - _site/assets/img/necie/news/necie-Identifies-Innovations-at-vha-shark-tank.jpg
 - _site/assets/img/necie/news/necie-wins-va-center-for-development.jpg
 - _site/assets/img/necie/news/soldierstrong.jpg
 - _site/assets/img/necie/news/tech-wheelchair.jpg
 - _site/assets/img/necie/news/transforming-transportation-for-homeless-veterans.jpg
 - _site/assets/img/necie/vha-drhci-logo.svg
 - _site/assets/img/necie/vha-necie-logo.svg
 - _site/assets/js/drhci-home-news
 - copy.js
 - _site/assets/js/necie-home-news
 - copy.js
 - _site/assets/js/necie-news.js
 - _site/assets/sass/vha/pages/drhci
 - copy/_index.scss
 - _site/assets/sass/vha/pages/drhci
 - copy/connect/_index.scss
 - _site/assets/sass/vha/pages/drhci
 - copy/director/_index.scss
 - _site/assets/sass/vha/pages/drhci
 - copy/masthead/_index.scss
 - _site/assets/sass/vha/pages/drhci
 - copy/mission/_index.scss
 - _site/assets/sass/vha/pages/drhci
 - copy/news/_index.scss
 - _site/assets/sass/vha/pages/necie/_index.scss
 - _site/assets/sass/vha/pages/necie/connect/_index.scss
 - _site/assets/sass/vha/pages/necie/director/_index.scss
 - _site/assets/sass/vha/pages/necie/masthead/_index.scss
 - _site/assets/sass/vha/pages/necie/mission/_index.scss
 - _site/assets/sass/vha/pages/necie/news/_index.scss
 - _site/necie/index.html
 - assets/img/necie/bubble-lines-sm.svg
 - assets/img/necie/bubble-lines.svg
 - assets/img/necie/genesis_de_la_cruz.jpg
 - assets/img/necie/kindred_kern.jpg
 - assets/img/necie/leandro_dasilva.jpg
 - assets/img/necie/lindsay-reigler.jpg
 - assets/img/necie/logo.svg
 - assets/img/necie/masthead-image.jpg
 - assets/img/necie/masthead-img.jpg
 - assets/img/necie/news/give.jpg
 - assets/img/necie/news/hero.jpg
 - assets/img/necie/news/mobius-mobility.jpg
 - assets/img/necie/news/move-the-sample.jpg
 - assets/img/necie/news/necie-Identifies-Innovations-at-vha-shark-tank.jpg
 - assets/img/necie/news/necie-wins-va-center-for-development.jpg
 - assets/img/necie/news/soldierstrong.jpg
 - assets/img/necie/news/tech-wheelchair.jpg
 - assets/img/necie/news/transforming-transportation-for-homeless-veterans.jpg
 - assets/img/necie/vha-necie-logo.svg
 - assets/js/necie-news.js
 - assets/sass/vha/pages/necie/_index.scss
 - assets/sass/vha/pages/necie/connect/_index.scss
 - assets/sass/vha/pages/necie/director/_index.scss
 - assets/sass/vha/pages/necie/masthead/_index.scss
 - assets/sass/vha/pages/necie/mission/_index.scss
 - assets/sass/vha/pages/necie/news/_index.scss
 - necie/index.html
 - _site/assets/css/styles.css
 - _site/assets/sass/vha/pages/_index.scss
 - _site/assets/sass/vha/pages/home/news-and-events/_index.scss
 - assets/css/styles.css
 - assets/sass/vha/pages/_index.scss
 - assets/sass/vha/pages/home/news-and-events/_index.scss

### CODE REVIEW

**Comment by RyanCrux** [comment]
https://dev-innovation.bgsandbox.com/ecosystem/views/national-centers/necie/index.html

**Review by will-bbg — CHANGES_REQUESTED** [review]
### General Items
1. Update URL for the NECIE card.
2. Update navigation link for NECIE on all NCI2I landing pages. 

### Carousel 
For the cards that do not link to an article, please remove the anchor wrapping the card. 

### Mobile
Make padding similar to the other landing pages. See screenshots below:

Our Mission bottom padding

Our Mission top padding

Caoursel bottom padding

**Comment by RyanCrux** [comment]
General Items
Update URL for the NECIE card.
DONE

Update navigation link for NECIE on all NCI2I landing pages.
DONE

Carousel
For the cards that do not link to an article, please remove the anchor wrapping the card.
DONE

Mobile
Make padding similar to the other landing pages. See screenshots below:
DONE

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
