### PR TITLE
Feat rl 6528211745 html css optimization

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

cleaned up and optimized HTML,CSS & JS. Also applied specifically requested reusable styles

## Related Tickets & Documents
- Monday Task #6528211745
https://blackberg-group.monday.com/boards/1931719392/pulses/6528211745

## QA Instructions, Screenshots, Recordings

Review changes and request any tweaks or updates to work towards using this page as a reusable template for upcoming pages.

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized 

## Changed Files in this Pull Request ##
- _includes/drhci/1_masthead.html
 - _includes/drhci/2_mission.html
 - _includes/drhci/3_news.html
 - _includes/drhci/4_director.html
 - _includes/drhci/5_connect.html
 - _site/assets/css/styles.css
 - _site/assets/sass/_uswds-theme-custom-styles.scss
 - _site/assets/sass/_uswds-theme.scss
 - _site/assets/sass/vha/pages/drhci/connect/_index.scss
 - _site/assets/sass/vha/pages/drhci/director/_index.scss
 - _site/assets/sass/vha/pages/drhci/news/_index.scss
 - _site/drhci/index.html
 - assets/css/styles.css
 - assets/sass/_uswds-theme-custom-styles.scss
 - assets/sass/_uswds-theme.scss
 - assets/sass/vha/pages/drhci/connect/_index.scss
 - assets/sass/vha/pages/drhci/director/_index.scss
 - assets/sass/vha/pages/drhci/news/_index.scss
 - drhci/index.html

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
I have a few changes Ryan:

- I see inline styles still being used. Reference this request: VA Internal Network tag should be using USWDS classes and not inline styles.
- Let's remove those new variables in the uswds-theme.scss. I'm seeing changes that I do not like. So, revert that back to what it was.
- Change the Director title text back to what it was previously.
- Remove the connect now button. It is not going anywhere and the live site doesn't have it showing either.

**Comment by RyanCrux** [comment]
* I see inline styles still being used. Reference this request: VA Internal Network tag should be using USWDS classes and not inline styles.
     -DONE - Sorry I missed this one, It was styled separately in a different file

* Let's remove those new variables in the uswds-theme.scss. I'm seeing changes that I do not like. So, revert that back to what it was.
     - DONE

* Change the Director title text back to what it was previously.
     - DONE

* Remove the connect now button. It is not going anywhere and the live site doesn't have it showing either.
     - DONE

* it appears that your branch doesn't have the hero background effect as it does on live. Please check that
     -DONE

**Review by will-bbg — CHANGES_REQUESTED** [review]
The tag appears to be a darker orange than what is on live or in the mockup. See below (Left-Branch   Right-Live)
Screenshot 2024-05-10 at 8 52 42 AM

**Comment by RyanCrux** [comment]
I picked the closest color that matched the USWDS standard classes after you asked to remove the custom theme color classes. I can add back a custom defined class to get the exact color. I can add a custom USWDS class again, create a regular css class, or return the inline style. Let me know how you want this edited and I'll get it done ASAP. Thanks! 
Screenshot 2024-05-10 at 10 04 27 AM

**Comment by RyanCrux** [comment]
Disregard. I found another color on a "Basic Palate" and it looks like it may be:  
Screenshot 2024-05-10 at 10 11 27 AM

I'll update...

**Comment by RyanCrux** [comment]
Sorry for the oversight! Fixed! 
Screenshot 2024-05-10 at 10 15 18 AM

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
