### PR TITLE
Feat/rl 7464841657/remove va ventures

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Remove VA Ventures from nav, national centers list, and map

## Related Tickets & Documents
- Monday Task: https://blackberg-group.monday.com/boards/1931719392/pulses/7464841657

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized 

## Changed Files in this Pull Request ##
- _includes/header-sub.html
 - _includes/header.html
 - _includes/home/national-centers.html
 - _site/assets/js/vendors/map-svg/mapsvg.functions.js
 - _site/drhci/index.html
 - _site/ideas/index.html
 - _site/index.html
 - _site/nc4ti/index.html
 - _site/necie/index.html
 - _site/va-ventures/index.html
 - assets/js/vendors/map-svg/mapsvg.functions.js

### CODE REVIEW

**Comment by RyanCrux** [comment]
Removed VA Ventures page link from nav. Also national centers section & map section onNCI2I home page: 
   https://www.dev-innovation.bgsandbox.com/ecosystem/views/national-centers/

**Review by ecstech-admin — COMMENTED** [review]
Seeing VA Ventures pin on map
image

**Comment by RyanCrux** [comment]
Clear you cashe or hard refresh. it's a JS change.

**Comment by RyanCrux** [comment]
@ecstech-admin Just saw your image... looks like a chrome only issue. i'm looking into it now

**Comment by RyanCrux** [comment]
fixed up @ecstech-admin - Please take another look
Screenshot 2024-09-19 at 1 53 49 PM

**Review by ecstech-admin — APPROVED** [review]
👍

**Pull request merged**
